# هذا الملف يُستخدم لضبط أداة تحليل الكود الثابت (linter) في فلاتر
# لإظهار التحذيرات والاقتراحات لتحسين الكود.

# 1. تضمين حزمة القواعد الأساسية الموصى بها من فريق فلاتر
# (تأكد من وجود "flutter_lints" في "dev_dependencies" بملف pubspec.yaml)
include: package:flutter_lints/flutter.yaml

linter:
  # 2. تحديد القواعد التي تريد تفعيلها أو تعديلها
  rules:
    # --- هذه هي القواعد التي طلبتها بخصوص "const" ---
    
    # T- إظهار تحذير عند إمكانية استخدام "const" لإنشاء الويدجت
    prefer_const_constructors: true
    
    # T- إظهار تحذير عند إمكانية تعريف متغير كـ "const"
    
    # T- إظهار تحذير للـ constructors في الكلاسات التي لا تتغير (immutable)
    
    # --- قواعد إضافية مفيدة جداً ---

    # T- تجنب استخدام دالة "print" في الكود النهائي
    # avoid_print: true # يمكنك تفعيلها عند تجهيز التطبيق للإطلاق


# 3. استثناء ملفات من التحليل (اختياري)
# analyzer:
#   exclude:
#     - 'lib/generated_plugin_registrant.dart'